apiVersion: v2
name: crossplane-github
description: A Helm chart to install crossplane-github provider
type: application
version: 0.1.4
appVersion: v0.18.0
maintainers:
  - name: thatmlopsguy
    url: https://thatmlopsguy.github.io
