# ArgoCD project configuration
# This project is used to manage addon applications in ArgoCD
# It defines the project name, namespace, and description
# The project is enabled by default and can be customized
# The project is used to group applications that are related to addons
argocdproject:
  enabled: true
  name: infra-addons
  namespace: argocd
  description: "Project for managing addon applications"

# Addons configuration
# Each addon can be enabled or disabled, and has its own configuration
# The addons will be deployed as ApplicationSets in ArgoCD
# The addons are defined with their respective Helm chart details
# and can be customized with selectors to filter the applications
addons:
  argocd2:
    enabled: false
    releaseName: argocd
    namespace: argocd
    chartRepository: https://argoproj.github.io/argo-helm
    chartName: argo-cd
    chartVersion: 8.1.3

  kyverno2:
    enabled: false
    releaseName: kyverno
    namespace: kyverno
    chartRepository: https://kyverno.github.io/kyverno
    chartName: kyverno
    chartVersion: 3.3.7

  feast:
    enabled: true
    releaseName: feast
    namespace: feast
    chartRepository: https://feast-helm-charts.storage.googleapis.com
    chartName: feast
    chartVersion: 0.50.0

  eraser:
    enabled: true
    releaseName: eraser
    namespace: eraser-system
    chartRepository: https://eraser-dev.github.io/eraser/charts
    chartName: eraser
    chartVersion: 1.3.1

  portainer:
    enabled: true
    releaseName: portainer
    namespace: portainer
    chartRepository: https://portainer.github.io/k8s
    chartName: portainer
    chartVersion: 1.0.69
