# ArgoCD project configuration
# This project is used to manage addon applications in ArgoCD
# It defines the project name, namespace, and description
# The project is enabled by default and can be customized
# The project is used to group applications that are related to addons
argocdproject:
  enabled: true
  name: addons
  namespace: argocd
  description: "Project for managing addon applications"

# Addons configuration
# Each addon can be enabled or disabled, and has its own configuration
# The addons will be deployed as ApplicationSets in ArgoCD
# The addons are defined with their respective Helm chart details
# and can be customized with selectors to filter the applications
addons:
  argocd:
    enabled: false
    releaseName: argocd
    namespace: argocd
    chartRepository: https://argoproj.github.io/argo-helm
    chartName: argo-cd
    chartVersion: 8.1.3

  kyverno:
    enabled: false
    releaseName: kyverno
    namespace: kyverno
    chartRepository: https://kyverno.github.io/kyverno
    chartName: kyverno
    chartVersion: 3.3.7
