{{- if eq .Values.environment "production" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-prod
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingressClass }}
{{- else }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-staging
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingressClass }}
{{- end }}
