apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-upjet-github
  namespace: crossplane-system
spec:
  package: crossplane-contrib/provider-upjet-github:{{ .Chart.AppVersion }}
