{{- range .Values.github.repositories }}
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: {{ .name }}
  namespace: crossplane-system
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/repositoryruleset
  labels:
    crossplane.io/managed-by: upjet
    testing.upbound.io/example-name: example
spec:
  forProvider:
    name: {{ .name }}
    description: {{ .description | default "Repository managed by Crossplane" }}
    visibility: {{ .visibility | default "public" }}
    gitignoreTemplate: {{ .gitignoreTemplate | default "Terraform" }}
    allowMergeCommit: {{ .allowMergeCommit | default true }}
    allowRebaseMerge: {{ .allowRebaseMerge | default true }}
    allowSquashMerge: {{ .allowSquashMerge | default true }}
    securityAndAnalysis:
    - secretScanning:
      - status: {{ .secretScanningStatus | default "false" }}
      secretScanningPushProtection:
      - status: {{ .secretScanningPushProtectionStatus | default "false" }}
  providerConfigRef:
    name: github-providerconfig
{{- end }}
