name: Check CODEOWNERS

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: install yq
        run: |
          sudo snap install yq

      - name: generate CODEOWNERS
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS

      - name: check CODEOWNERS for modifications
        run: |
          git diff --exit-code || echo "::warning::There is at least one codeowner mismatch."
